// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        pgtype.UUID
	Name      pgtype.Text
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type Dislike struct {
	NewsID pgtype.UUID
	UserID pgtype.UUID
}

type HasCategory struct {
	NewsID     pgtype.UUID
	CategoryID pgtype.UUID
}

type Like struct {
	NewsID pgtype.UUID
	UserID pgtype.UUID
}

type News struct {
	ID          pgtype.UUID
	Author      pgtype.Text
	Title       pgtype.Text
	Description pgtype.Text
	Url         pgtype.Text
	ImageUrl    pgtype.Text
	PublishAt   pgtype.Timestamp
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	DeletedAt   pgtype.Timestamp
}

type User struct {
	ID        pgtype.UUID
	AuthID    string
	Email     pgtype.Text
	Name      pgtype.Text
	Role      pgtype.Text
	ImageUrl  pgtype.Text
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}
